# Generated by Django 2.2.2 on 2019-07-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('model_code', models.CharField(max_length=32, unique=True, verbose_name='菜单code')),
                ('model_url', models.CharField(max_length=32, verbose_name='菜单url')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('role_describe', models.CharField(max_length=64, verbose_name='角色描述')),
                ('model', models.ManyToManyField(to='rbac.Model', verbose_name='规则表')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话')),
                ('is_active', models.BooleanField(default=1)),
                ('create_datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_dateimte', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录日期')),
                ('roles', models.ManyToManyField(to='rbac.Role', verbose_name='角色')),
            ],
        ),
    ]
